### PR TITLE
Use nslsii.configure_base(...)

### LINKED ISSUE #52: Use nslsii.configure_base in startup/00-nsls2-tools.py
Currently, it's not used. Need to replace the explicit definitions of RE, db, etc. in [`startup/00-nsls2-tools.py`](https://github.com/NSLS-II-CSX/xf23id1_profiles/blob/master/profile_collection/startup/00-nsls2-tools.py) -> [`startup/csx1/startup/startup.py`](https://github.com/NSLS-II-CSX/xf23id1_profiles/blob/master/profile_collection/startup/csx1/startup/startup.py) with `nslsii.configure_base(...)`. That will bring better control of the instantiated things and the default logging configuration.

### PR DESCRIPTION
**Pull request by mrakitin**
Resolves #52.

This PR contains commits from #53, so that one should be merged prior to this PR.

### CODE REVIEW

**Review by AbbyGi — APPROVED** [review]
Looks good.

**Review by ambarb — APPROVED** [review]
@mrakitin answer questions I wrote in line of code.

**Comment by mrakitin** [comment]
Thanks for your review, @ambarb! I did not see any questions. Did you submit them with your review? Or was everything answered during my visit on Monday?

**Comment by mrakitin** [comment]
It was tested thoroughly at the beamline by @ambarb, merging.

**Pull request merged**
