### PR TITLE
WIP: blind attempt to get daig6 useable as a monitor device

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @ambarb 

The read and configuration attrs may need to be adjusted and this may not have enough plugins configured.

**Comment by ambarb** [comment]
@tacaswell this looks good.  I thing we can merge, but is it possible to choose one of the two options so I don't break something for someone else until things are fully tested

```python
diag6 = NoStatsCam('XF:23ID1-BI{Diag:6-Cam:1}', name='diag6')
#diag6 = MonitorStatsCam('XF:23ID1-BI{Diag:6-Cam:1}', name='diag6')
```

```python
diag6 = NoStatsCam('XF:23ID1-BI{Diag:6-Cam:1}', name='diag6')
diag6_v2 = MonitorStatsCam('XF:23ID1-BI{Diag:6-Cam:1}', name='diag6_v2')
```

**Comment by ambarb** [comment]
I can of course do this once we merge and git pull if it is easier.  Just let me know what your preference is.

**Comment by tacaswell** [comment]
That is probably easier (at least for me!)

**Comment by ambarb** [comment]
everything seems to work.  I just need the beam to come back for final testing.

Also, I did not ask for this part, but I do see that if I change the number of images to be something other than 1 (`diag6.cam.num_exposures`) this does't seem to work.  Onto the next point after a single trigger.  Unsure if this is a consequence of the AD for the proslica GT1920.  @johnsinsheimer do you know?

**Comment by johnsinsheimer** [comment]
I'm not sure how num_exposures works with triggering and would have to test.  You can look at 

ADNumExposuresCounter | asynInt32 | r/o | Counter that increments by 1 each time an exposure is acquired for the current image.           Driver resets to 0 when acquisition is started. | NUM_EXPOSURES_COUNTER | $(P)$(R)NumExposuresCounter_RBV | longin
-- | -- | -- | -- | -- | -- | --


To see if it counts up when you try more than 1.

**Comment by ambarb** [comment]
XF:23ID1-BI{Diag:6-Cam:1}cam1:NumExposures
is the PV.  If I change the PV by hand,  bluesky is not aware, and moves on to the next point in mid-collection.  

Reason wondered about this is because I realized there is no "switch" to disable the sclr being triggered by the TTL pulse of the FCCD.  WIll speak to chanaka about the soft-glu and maybe we can fix it there.   I am not sure this other approach (with number of images) would even work.  

Another option is 2 soft-glue, one just to provide some method of having an acurrate clock for 0.3ms exposures in free-run.

**Pull request merged**
